### ISSUE TITLE
where is your paper

### ISSUE THREAD

**Issue by Jinyong-Huang** [haofeixu/aanet#1]
can't find your paper, would you give me a link?

**Comment by haofeixu** [comment]
Thanks for your interest.
Our paper should be available on arXiv tomorrow.

**Comment by Jinyong-Huang** [comment]
great.&nbsp;



---Original---

**Comment by haofeixu** [comment]
https://arxiv.org/abs/2004.09548

**Comment by Jinyong-Huang** [comment]
wonderful jobs!

**Comment by Jinyong-Huang** [comment]
![image](https://user-images.githubusercontent.com/55069241/81788176-b4a87b80-9534-11ea-9449-43d4a4ff61f1.png)

**Comment by Jinyong-Huang** [comment]
run AANet and AANet+ scripts,  len(pred_disp_pyramid) is always 5!!!!!!!!!!!!!!

**Comment by haofeixu** [comment]
Yes, you are right. It's a typo in the comments and will not affect the model.

**Comment by Jinyong-Huang** [comment]
thank you for your reply!

**Comment by Jinyong-Huang** [comment]
![image](https://user-images.githubusercontent.com/55069241/82000972-850c8700-968c-11ea-973e-03a11dd3502b.png)

when I modify the max_disp's value, like 48. but can't load pretrained model. the error is  "....size mismatch for...."
how can i successfully load the AANet+'s pretrained mode if i have to modify the max_disp.

**Comment by haofeixu** [comment]
You can manually exclude the aggregation part of the model weights and load remaining weights.

**Comment by Jinyong-Huang** [comment]
为了表达清楚，我用中文发了。
当我在训练其它数据集时，视差范围改成-48到+48，训练过程当中，最后的输出(pred_disp_pyramid)前三项是正常的,都是成倍数关系，但是后两项视差优化的输出结果明显有误。最后发现在求左图误差的时候求得的值特别大。不太明白refinement.py里面的disp_warp操作，如果我改变了视差范围(有负号)，请问该怎么修改disp_warp代码。

**Comment by Jinyong-Huang** [comment]
![image](https://user-images.githubusercontent.com/55069241/82778196-47291300-9e83-11ea-9521-bedac728ac6a.png)
![image](https://user-images.githubusercontent.com/55069241/82778206-50b27b00-9e83-11ea-9103-18cc1daa10f5.png)

**Comment by Jinyong-Huang** [comment]
可能是relu造成的。把负视差变为了0。
disp = F.relu(disp + residual_disp, inplace=True)  # [B, 1, H, W]
