### ISSUE TITLE
bash build.sh error

### ISSUE THREAD

**Issue by jingfenglanyun** [haofeixu/aanet#11]
env:  python 3.6  torch 1.5  torchvision 0.6

error information ： deform_conv_cuda.cpp:417:3: error: ‘AT_CHECK’ was not declared in this scope

**Comment by jingfenglanyun** [comment]
solution：
modify all 'AT_CHECK' to 'TORCH_CHECK'

**Comment by haofeixu** [comment]
Our framework is developed with pytorch 1.2, we recommend installing the exactly same version for convenience.
