### ISSUE TITLE
Prediction use pretrained network on CPU

### ISSUE THREAD

**Issue by LongshengDu** [haofeixu/aanet#13]
Can I build deformable convolution without cuda and run pretrained network on CPU? Just want to do some tests and currently not have a nvidia card.

When I run predict.py, I got

> ImportError: cannot import name 'deform_conv_cuda' from 'nets.deform_conv' 

When I build deformable convolution, I got

> AssertionError: Torch not compiled with CUDA enabled

**Comment by haofeixu** [comment]
Sorry you can't. You can refer to https://github.com/haofeixu/aanet/issues/10
