### ISSUE TITLE
slightly confused about where the speed up came from

### ISSUE THREAD

**Issue by hua-wu-que** [haofeixu/aanet#15]
Hi!

After reading your paper, I am not very clear how the speed up came from. 

From my understanding, traditional cost volume approach build cost volume of size BXCXDXHXW, 
but in your approach you compute the dot product between two features, which results in BXDXHXW . 

Is this where the speed up came from?

Thank you for your reply!

**Comment by haofeixu** [comment]
Cost aggregation on a 4D cost volume is significant faster than a 5D counterpart, you can check the **Complexity Analysis** part in Section 4.4 of our paper.
