### ISSUE TITLE
FLOPs 是如何得出的

### ISSUE THREAD

**Issue by JumpXing** [haofeixu/aanet#16]
请问下你们的各个模型的FLOPs 是如何得出的？
是只计算了CONV中的MAC次数，还是计算量CONV、BN、activate function、pooling等所有的

**Comment by haofeixu** [comment]
The FLOPs is measured for conv layers only and you can refer to this repo: https://github.com/Lyken17/pytorch-OpCounter

**Comment by JumpXing** [comment]
Thanks  for your explaining. We also used this tool but got a different result of FLOPs from yours. Now I know that reason is that  our result contains not only CONV but also BN, pooling and so on.

**Comment by lelelexxx** [comment]
> Thanks for your explaining. We also used this tool but got a different result of FLOPs from yours. Now I know that reason is that our result contains not only CONV but also BN, pooling and so on.

Hi!
I'm also curious about the FLOPs of network, Could you please tell me which libs or tools did you use for FLOPs calculation? Thanks a lot!
