### ISSUE TITLE
ImportError: cannot import name 'deform_conv_cuda'

### ISSUE THREAD

**Issue by prabhuiitdhn** [haofeixu/aanet#20]
I am working on anaconda (in Windows), I have followed the mentioned steps for installation, But I am getting this error.
```

from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda'
```
Please help.

**Comment by haofeixu** [comment]
Have you successfully installed the deformable conv op? Could you please give more details about when this error occurs?

**Comment by prabhuiitdhn** [comment]
Yeah, I think so, I am working on anaconda in Windows, so I was not able to run the build.sh file but I ran the command '$PYTHON setup.py build_ext --inplace' in anaconda prompt.
```
#!/usr/bin/env bash

PYTHON=${PYTHON:-"python"}

if [ -d "build" ]; then
    rm -r build
fi
$PYTHON setup.py build_ext --inplace

```

Is there any way to do that in windows?

**Comment by haofeixu** [comment]
I think you are right, but you may want to refer to [this issue](https://github.com/open-mmlab/mmdetection/issues/1088) to resolve the error since I have never tested my code on windows, sorry about that.

**Comment by prabhuiitdhn** [comment]
Hi @haofeixu, Thanks for replying. But is it restricted to have cuda10.0? Bcz Even after setting it up in linux pc I am getting the same error. 

Currently, I have ubuntu with cuda 9.0 and pytorch 1.5.0, will this run?

**Comment by haofeixu** [comment]
I think cuda 9.0 should be okay, but I am not sure whether cuda 9.0 is supported by pytorch 1.5.0. You can check that by running `torch.cuda.is_available()`, if the output is False, you may need to downgrade pytorch to 1.1.0. 

However, you are highly recommanded to use exactly same version (cuda 10.0 and pytorch 1.2.0) as ours to avoid version conflicts.
