### ISSUE TITLE
About the result of StereoNet in the paper

### ISSUE THREAD

**Issue by xy-guo** [haofeixu/aanet#23]
In your paper, the time of stereonet is 0.015s. It is really fast. Can you share your implementation? I tried to reimplement StereoNet last year but failed to get a speed performance like this. Thank you so much!

**Comment by haofeixu** [comment]
We have included the implementation of StereoNet in our framework, you can combine different components with the following config:
```
--feature_type stereonet
--feature_similarity difference
--num_downsample 3
--aggregation_type stereonet
--refinement_type stereonet
``` 
However, we are also unable to reproduce the time of 15ms (see Table 2 of our paper, we got 23ms).

**Comment by xy-guo** [comment]
Thank you so much! I will check it later.
