### ISSUE TITLE
The problem of cuda?

### ISSUE THREAD

**Issue by xuzhongyou** [haofeixu/aanet#25]
The readme writes the cuda version is 10.0 that means the cudatoolkit in pytorch or the cuda version in /usr/local/cuda，i think the build work is by the /usr/local/cuda. i meet the segmentation fault, and not sure the problem comes from cuda version. The cuda version in my path is cuda9.2 and the pytorch environment follow the environment.yaml.

**Comment by haofeixu** [comment]
Have you successfully installed pytorch with cuda support (you can check the output of running `torch.cuda.is_available()`)? Could you please post more error messages? Thanks.
