### ISSUE TITLE
Memory consumption measurement

### ISSUE THREAD

**Issue by MJITG** [haofeixu/aanet#29]
Hi,  @u@haofeixu ,
 
 In table.2 of your paper, there is a list of comparisons with four representative stereo models. Your method saves a lot of memory when equipped to other models. I'm confused about the number of memory consumption because mine is kind of different from yours. Could please tell me how you measure the memory consumption since I guess different measurement may cause different results.

**Comment by haofeixu** [comment]
We simply report what `nvidia-smi` shows.

**Comment by MJITG** [comment]
OK I get it
