### ISSUE TITLE
the performace without deformable conv?

### ISSUE THREAD

**Issue by meteorshowers** [haofeixu/aanet#3]
can you provide the performace without deformable conv?

**Comment by meteorshowers** [comment]
Moreover,
I test your model with normal convolution,100ms on titanxp
is the runtime right?

**Comment by haofeixu** [comment]
You can refer to the Table 1 in our paper for the performance without deformable conv.

May I know your test settings (e.g., resolution)? Our inference time is measured by `inference.py`  with `--count_time` activated.

**Comment by meteorshowers** [comment]
Thanks
360*1280
I do not use the  deformable conv.

**Comment by haofeixu** [comment]
Are you using our code `inference.py`?

**Comment by meteorshowers** [comment]
no

**Comment by meteorshowers** [comment]
why do not eval on the 1/8 resolution with stereonet config?
It would be faseter

**Comment by haofeixu** [comment]
There is a trade-off between accuracy and speed. If speed is a priority, you can use the StereoNet-AA model.

**Comment by meteorshowers** [comment]
If anyone test the inference time on titanxp, 
tell me,
thanks

**Comment by haofeixu** [comment]
We have uploaded our timing scripts, you should use them to measure the inference time.

**Comment by meteorshowers** [comment]
118.24091136 gflops 3.175282 M
double check parameter 3.175282 M
time 114.790651798 ms
input 360*1260
device titian xp
I think v100 may 1.5 times faster than titianxp, it is normal

**Comment by wangzhao88** [comment]
> 118.24091136 gflops 3.175282 M
> double check parameter 3.175282 M
> time 114.790651798 ms
> input 360*1260
> device titian xp
> I think v100 may 1.5 times faster than titianxp, it is normal

您好，能否支援一份不带dconv的代码？

**Comment by yanzhou-li** [comment]
can you share me the code without   @@deformable


> can you provide the performace without deformable conv?

can you share me the code without deformable,thank you! @meteorshowers
