### ISSUE TITLE
FLOPs for networks

### ISSUE THREAD

**Issue by lelelexxx** [haofeixu/aanet#30]
This issue is related to #27, In case you didn't notice the question in it, I propose a new one.
I have set 1x3x576x960 as input and only take conv layers(include both 2d and 3d conv and transpose conv) into account, and get 1.08T FLOPs for PSMNet using pytorch-OpCounter. Is there anything wrong in my setting? Could you please provide the FLOPs detailed information? for example the custom ops? Any reply will be appreciated!
Thanks!

**Comment by haofeixu** [comment]
I will upload our implementation later.

**Comment by haofeixu** [comment]
Uploaded.
