### ISSUE TITLE
Bad prediction results when use pretrained model

### ISSUE THREAD

**Issue by Hahaemmm** [haofeixu/aanet#31]
When I try to run the predict file using the pictures I took, I get very poor prediction results. Is there something wrong with me?

![QQ截图20200723223836](https://user-images.githubusercontent.com/49722029/88299729-4868a600-cd35-11ea-9f1f-f19eb44d21f5.jpg)

**Comment by haofeixu** [comment]
I believe there is something wrong in your config. Can you successfully run our demo (https://github.com/haofeixu/aanet/blob/master/scripts/aanet_predict.sh)?

**Comment by Hahaemmm** [comment]
I can run your demo successfully

**Comment by haofeixu** [comment]
Have your pictures been rectified? Alternatively, can you send your pictures to me (xhf@mail.ustc.edu.cn)? Thanks!

**Comment by sunshinnnn** [comment]
I meet similar bug when using your pretrained StereoNet - AA. 
Here is my predict script
```
#!/usr/bin/env bash

# Predict
CUDA_VISIBLE_DEVICES=1 python predict.py \
--data_dir demo \
--pretrained_aanet pretrained/stereonet-aa_sceneflow-1fbe2dea.pth \
--feature_type stereonet \
--feature_similarity difference \
--num_downsample 3 \
--aggregation_type stereonet \
--refinement_type stereonet \
--no_intermediate_supervision
```
Could tell me more about your StereoNet - AA, since you didn't make it clear how to use this model and what is the meaning of -AA.

**Comment by haofeixu** [comment]
We have included the inference script for StereoNet-AA(https://github.com/haofeixu/aanet/blob/master/scripts/stereonet-aa_inference.sh), and AA means replacing the cost aggregation architecture with our proposed Adaptive Aggregation modules (we have made it clear in our paper).

Your config is not correct, you can refer to https://github.com/haofeixu/aanet/blob/master/scripts/stereonet-aa_inference.sh for the correct usage.

**Comment by sunshinnnn** [comment]
COOL! Thanks!  And **Sorry**  for missing the inference script of stereonet... Really good code structure and nice response.
