### ISSUE TITLE
error in running aanet_predict.sh

### ISSUE THREAD

**Issue by xuzhongyou** [haofeixu/aanet#34]
<img width="982" alt="屏幕快照 2020-08-10 下午1 57 18" src="https://user-images.githubusercontent.com/16487416/89755308-8e818000-db11-11ea-90c5-f05aa254bcfc.png">

after dubug, i find the problem comes from deconv,but no error happen in building
my Cuda version:
<img width="470" alt="屏幕快照 2020-08-10 下午3 34 19" src="https://user-images.githubusercontent.com/16487416/89760507-22a61400-db1f-11ea-94f6-5fa7c87e03cf.png">

pytorch version:
pytorch1.2.0
cuda Driver version:
<img width="555" alt="屏幕快照 2020-08-10 下午3 36 06" src="https://user-images.githubusercontent.com/16487416/89760585-45382d00-db1f-11ea-891c-26405f311dbb.png">

the file exists
<img width="868" alt="屏幕快照 2020-08-10 下午3 37 16" src="https://user-images.githubusercontent.com/16487416/89760672-6bf66380-db1f-11ea-96d5-97b7ddb171f6.png">

**Comment by xuzhongyou** [comment]
I solved it by changing the version of gcc

**Comment by Estrella1024** [comment]
I would like to ask, how did you change it through gcc?
