### ISSUE TITLE
Correlation in cost volume

### ISSUE THREAD

**Issue by jbohnslav** [haofeixu/aanet#4]
https://github.com/haofeixu/aanet/blob/f27ec42e3c3c8482d1ca49076ed56b1993aa1028/nets/cost.py#L40-L48

Hi there,

The paper looks great. Thanks for releasing your code! I noticed that in the "correlation" type of cost volume construction, you used the mean of the elementwise product of two feature vectors instead of the traditional dot product, which DispNetC and FlowNet (the original) used. Of course, this is just a scaled version. Can you talk about why you scaled it this way? Thank you!

**Comment by haofeixu** [comment]
Hi @jbohnslav ,

Thanks for your interest! Our intuition is that the scaled version can potentially prevent very large values, but the actual difference may be very small.

**Comment by jbohnslav** [comment]
Thanks! It's certainly easier to read this way, and should hopefully be less dependent on the dimensionality of your input features to the cost volume. Thanks again for the code and paper.

**Comment by kwea123** [comment]
This correlation, if I am right, first appeared in [gwcnet](https://github.com/xy-guo/GwcNet)

https://github.com/xy-guo/GwcNet/blob/0987074f48b098c6e975a58ca5aacf233b0fb0eb/models/submodule.py#L44-L63

The code is almost the same. Don't know if it's actually the first though, if I'm wrong correct me.

**Comment by haofeixu** [comment]
It was already used in PWC-Net (https://arxiv.org/abs/1709.02371) before.
