### ISSUE TITLE
Question about D1 metric

### ISSUE THREAD

**Issue by LeoCho1learning** [haofeixu/aanet#41]
Hi, thank you for your nice work.
I have a question about the calculation of the d1 metric in your code.
err_mask = (e > 3) & (e / d_gt > 0.05) (line 23 in metric.py)

In kitti benchmark, it says that a correctly estimated pixel should have the disparity error less than 3px or <5%.

But it seems that you are using 'and' instead of 'or'.

So I'm a littile confused, could you explain this?

**Comment by haofeixu** [comment]
Here we are measuring **wrong** pixels (i.e., > 3px and > 5%).
