### ISSUE TITLE
Running time mentioned in Table 3 

### ISSUE THREAD

**Issue by FlyingGaifield** [haofeixu/aanet#44]
I noticed that in table3, you mentioned EPE/Time of StereoNet is 1.1 and 0.015.
I also read the original paper of StereoNet, maybe "0.015s" using the fast(16x, single) version and "1.1 "using the best(8x,multi) version. Can you explain it more?

**Comment by haofeixu** [comment]
The EPE and time are directly taken from the original StereoNet paper, both are measured by the `8x, multi` model (you can refer to Table 1 and 2 in StereoNet paper).

**Comment by FlyingGaifield** [comment]
> The EPE and time are directly taken from the original StereoNet paper, both are measured by the `8x, multi` model (you can refer to Table 1 and 2 in StereoNet paper).

 From the implementation of https://github.com/meteorshowers/StereoNet-ActiveStereoNet
While using `8x, single,` he can only get 30FPS with epe 1.38. I doubt that 0.015 is not corresponding to `8x, multi`
