### ISSUE TITLE
why do we can't multiply scale in file model.py when interpoate the pred_disp?

### ISSUE THREAD

**Issue by dreamhua82** [haofeixu/aanet#45]
Hi, I have two questions to ask you.
1、In your model.py  # line 97, why don't multiply the resize scale as do in refinement module?
Is that mean, we have finished training, This is the last result, so we don't multiply the scale any more  when we do interpolate?
2、why don't use the full resolution to construct multi-scale cost volume. (i.e.  H, H/2, H/3),  is that only for save GPU memory?
Thanks,

**Comment by haofeixu** [comment]
1. the scale factor is acutally multiplied: https://github.com/haofeixu/aanet/blob/f689abf81ef072b4e50eb480d3a73db66eebda44/model.py#L97-L98

2. Of course you can use full resolution, but it will cost too much memory.
