### ISSUE TITLE
the KITTI epe results

### ISSUE THREAD

**Issue by zyl1336110861** [haofeixu/aanet#46]
Hi, haofei
I want to know how to get  the KITTI2015 epe results of Table1 in your paper?  Just execute the second finetune step(whole set or just 160 images?) in 4.2 section or execute the two steps(the mix training set and separate training sets)? Thank you so much!

**Comment by zyl1336110861** [comment]
@haofeixu Hi,haofei, I have downloaded the pretrained model trained on Sceneflow. But when I finetune the model on 160images of kitti2015, I can not get the epe results(1.4+instead of 0.68) shown in your paper. I am very confused about the my process. Can you tell me the detailed finetune method? Thank you very much!

**Comment by Wyx9352** [comment]
How to evaluate the data set of kitti15? kitti did not give gt in the test folder.

**Comment by haofeixu** [comment]
The results in Table 1 is obtained on KITTI training set. You can find this information from our paper.
![image](https://user-images.githubusercontent.com/19343475/201505448-ca3a993f-8c0b-4f21-8ac6-13af8bc1b772.png)
