### ISSUE TITLE
how to fine-tuned model to predict the disparity map, no additional training is done on Middlebury

### ISSUE THREAD

**Issue by lawo123** [haofeixu/aanet#48]
how to fine-tuned model to predict the disparity map, no additional training is done on Middlebury ?
how to show image have color like below?
![image](https://user-images.githubusercontent.com/44777088/97839302-e4368480-1d1c-11eb-8bc3-06f6eb25ba70.png)

**Comment by haofeixu** [comment]
You can use the prediction script to generate the disparity map on any image pair: https://github.com/haofeixu/aanet/blob/master/scripts/aanet_predict.sh

The disparity map is visualizaed with `plasma` colormap, which can be implemented with matplotlib.
