### ISSUE TITLE
Some questions about inference on PSMnet

### ISSUE THREAD

**Issue by zcong17huang** [haofeixu/aanet#49]
Because of the version problems, I haven't been able to run your code. I'm trying to read your code to get a better understanding of your work.
I'm a little confused when i try to understand the construction of **PSMNet-AA**. You use the [PSMNetFeature](https://github.com/haofeixu/aanet/blob/master/nets/feature.py#L233) to extract feartures to construct cost volumes. Although you make a [volume list](https://github.com/haofeixu/aanet/blob/master/nets/aanet.py#L146), it actually has only one cost volume. So when you use **AdaptiveAggregation**, default num_scales = 3, how could you use **CSA** In this case? I think there would be an error when running [`assert len(self.branches) == len(x)`](https://github.com/haofeixu/aanet/blob/master/nets/aggregation.py#L376), because len(self.branches) = num_scales = 3, but len(x) = 1. 
So where did I get it wrong?  Looking forward to your reply and you pointing out my mistake.
Extremely grateful！

**Comment by haofeixu** [comment]
We have constructed an additional feature pyramid for PSMNet feature.
