### ISSUE TITLE
Disparity Refinement

### ISSUE THREAD

**Issue by youmi-zym** [haofeixu/aanet#5]
Thanks for your brilliant work.  May I ask the performance of your AANet or AANet+ after removing the refinement module. Thanks. 
By the way, I know there is no implementation of 3D deformable convolution, have you thinking about implementing it and releasing  3D ISA and CSA?

**Comment by haofeixu** [comment]
Thanks for your interest. 
Unfortunately, we didn't have such a comparison. However, we anticipate the performance will be not that good, as the resolution of estimated disparity without refinement is relatively low and the residual learning (i.e., refinement) scheme has been proved to be effective in many previous works (e.g., StereoNet). You can train with our code to see what happens.
Sorry about that we have no plan to extend the deformable conv to 3D currently.

**Comment by youmi-zym** [comment]
Thanks

**Comment by Todd-Qi** [comment]
Hello, thanks for your great work.
As I know, the `scale_factor` is the ratio of left_img Height and low_disp Height.
But, why the `disp` need to multiply the `scale_factor`?

https://github.com/haofeixu/aanet/blob/5e2359cfea9c38ebcddf5e750ec9ad1ac92725fc/nets/refinement.py#L45-L47

**Comment by haofeixu** [comment]
Hi @Todd-Qi ,

As the low resolution disparity is upsampled to higher resolution, it's magnitude needs to be scaled correspondingly.
That is, a 1-pixel disparity at 1/4 resolution corresponds to 2-pixel for 1/2 resolution.

**Comment by Todd-Qi** [comment]
Thanks for your clear explanation.
