### ISSUE TITLE
About Table 4 in your paper

### ISSUE THREAD

**Issue by yanzhou-li** [haofeixu/aanet#53]
dear authors:
     when i run your script `aanet_train.sh` on  KITTI 2015 ,i got the disparity images on`KITTI_2015_test`datasets.that's cool!
above all,i want to compare with the gt images(like table 4 in your paper) and analyze the error,how can i do that?can you help me? 
tks!
@haofeixu  @Ilya-Muromets @trigal

**Comment by haofeixu** [comment]
You need to submit to KITTI evaluation server.
