### ISSUE TITLE
About Correlation layer  and can you share me the code without deformable conv

### ISSUE THREAD

**Issue by yanzhou-li** [haofeixu/aanet#57]
i come back again. Drive into the theme,I want to know if I use the `concat`and `convolution` instead of `correlation`,the net can work? if it works, how can I do that,thanks!
 @haofeixu @Ilya-Muromets

**Comment by haofeixu** [comment]
@yanzhou-li , yes, our implementation supports both cost volume construction methods, you can check the `--feature_similarity` argument in `train.py`.

**Comment by haofeixu** [comment]
BTW, if you don't want to use the deformable conv, you can set the `--num_deform_blocks` to 0 in `train.py`.

**Comment by yanzhou-li** [comment]
i got it. thank you
