### ISSUE TITLE
How to calculate distance of the object from the output (Depth map) of the model?

### ISSUE THREAD

**Issue by aditdoshi333** [haofeixu/aanet#58]
Hello,

Thanks for publishing such good work. I am using the architecture for inference using stereo camera stereo. I want to calculate the distance of the object from the output of the model. Can anyone please throw some light for the same?

Thank you

**Comment by haofeixu** [comment]
Hi, you need the info of camera baseline `b` and focal length `f`, then the depth can be computed by `bf/d`, where `d` is the predicted disparity map.

**Comment by aditdoshi333** [comment]
> Hi, you need the info of camera baseline `b` and focal length `f`, then the depth can be computed by `bf/d`, where `d` is the predicted disparity map.

Hi Yeah, I have to baseline and focal length but not sure about the disparity map parameter. So d is the pixel value of the particular coordinate?

**Comment by haofeixu** [comment]
Yes.

**Comment by aditdoshi333** [comment]
> Yes.

Thanks a lot for the prompt reply. Just one last question I don't have to do any processing with the disparity map? Just feeding the pixel value in the formula will do the thing right?

**Comment by haofeixu** [comment]
Yes, no processing is required. You can have a try.
