### ISSUE TITLE
low contrast image warning 

### ISSUE THREAD

**Issue by aditdoshi333** [haofeixu/aanet#59]
Hello,
I am trying to use predict.py for inference on a custom image stereo pair. But consistently I am getting the warning of low contrast images. I tried with different images but still, the warning is the same.

**Comment by aditdoshi333** [comment]
This is the precise warning I am getting.

/home/mrobotics2/anaconda3/envs/aanet/lib/python3.7/site-packages/skimage/io/_io.py:141: UserWarning: dataset/pred/right_rect_p0_0_pred.png is a low contrast image
  warn('%s is a low contrast image' % fname)

Input:
**Left** 
![left_rect_p0_0](https://user-images.githubusercontent.com/23434856/107355593-b5873180-6af5-11eb-85e6-9956c6cf049b.png)


**Right**
![right_rect_p0_0](https://user-images.githubusercontent.com/23434856/107355664-cc2d8880-6af5-11eb-8a73-3cc808933a90.png)

**Output from the network**
![left_rect_p0_0_pred](https://user-images.githubusercontent.com/23434856/107355766-f2ebbf00-6af5-11eb-809e-a96a0f598ccd.png)

**Comment by haofeixu** [comment]
On possible reason can be that the images are not loaded correctly, thus the network is not able to produce reasonable output. Also, our network assumes rectified images as input.

**Comment by aditdoshi333** [comment]
I am rectifying the images. What do you mean by images not loaded properly?

**Comment by haofeixu** [comment]
Are you runing our `predict.py` for prediction? The input images are firstly loaded to [0, 1], then normalization is applied. You can refer to the code here: https://github.com/haofeixu/aanet/blob/f689abf81ef072b4e50eb480d3a73db66eebda44/predict.py#L134-L138

**Comment by aditdoshi333** [comment]
I am running predict.py only. And input images are getting loaded I checked that but then this warning of skimage is coming

warn('%s is a low contrast image' % fname)

**Comment by haofeixu** [comment]
Are you able to run our demo `bash scripts/aanet_predict.sh` successfully?

**Comment by raylihaut** [comment]
I have the same problem. I use KITTI2012 and KITTI2015 to test the trained model and the network outputs "**** is a low contrast image". How can I solve the problem?

**Comment by JiazhiLiu** [comment]
I also met the same problem, but finally found that it is because I did not load the right pretrained annet parameters. Make sure the right file ".pth" is on the folder.
