### ISSUE TITLE
Deformable conv initialization?

### ISSUE THREAD

**Issue by dreamhua82** [haofeixu/aanet#61]
Hi, I noticed that in deform.py file the offset conv's weights are initialized by these codes (line 67,68):
           nn.init.constant_(self.offset_conv.weight, 0.)
           nn.init.constant_(self.offset_conv.bias, 0.)

But in resnet.py file there are another initialization codes (line 136-141):
          for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
I wonder whether the latter code influence the previous code to initialize the offset conv??

Thanks.

**Comment by haofeixu** [comment]
Hi @dreamhua82 , thanks for pointing this out. Yes, you are right, but it will only affect the initialization of the resnet feature. For other modules (e.g., aggregation and refinement), the offset conv initialization will take effect. You can also try our AANet+ model, which doesn't have this problem and enjoys better performance. Thanks.

**Comment by dreamhua82** [comment]
Hi, thanks for your kind reply.
Can I only use your deformable conv in PSMNet to substitute some of the conv (e.g., in feature extraction module) to get a better performance than original PSMNet(not use AAModule)?

**Comment by haofeixu** [comment]
You can try to make a comparison, but the improvement may be marginal.
