### ISSUE TITLE
Cannot get correct results

### ISSUE THREAD

**Issue by raylihaut** [haofeixu/aanet#63]
Hi, haofei, I retrained the model with KITTI2012，and I configured the environment exactly according to README, but the trained network cannot output the right results.  The following image is an example output.  Can you give me an indication of what's wrong? Thanks.
![000000_10_pred](https://user-images.githubusercontent.com/20202866/115170025-395f2a80-a0f2-11eb-8e9f-86e223d7db87.png)

**Comment by Ocelot7777** [comment]
The same question. I just run aanet_predict.sh with nothing changed.

**Comment by haofeixu** [comment]
Closing since this issue has been resolved via email.
