### ISSUE TITLE
ValueError: cannot reshape array of size 6139 into shape (540,960)

### ISSUE THREAD

**Issue by old-popsicle** [haofeixu/aanet#65]
I encountered the following problems while running the program:

ValueError: cannot reshape array of size 6139 into shape (540,960)

![QQ图片20210527152638](https://user-images.githubusercontent.com/72902369/119783775-21a07080-bf00-11eb-8456-e2702757a403.png)

Excuse me, what went wrong with this?

**Comment by old-popsicle** [comment]
@haofeixu I would appreciate if you can tell me how to solve the problem

**Comment by haofeixu** [comment]
Hi @old-popsicle , could you please provide more info regarding the error, for example, the running script, thanks.

**Comment by old-popsicle** [comment]
This is how I run the program&nbsp; &nbsp; “bash scripts/aanet_train.sh”&nbsp; &nbsp; &nbsp;Because of the GPU, I put the batch_ size is set to 1, and an error occurs&nbsp; &nbsp;ValueError: cannot reshape array of size 6139 into shape (540,960)
I appreciate your willingness to help me solve this problem&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haofei ***@***.***&gt;; 
发送时间: 2021年5月28日(星期五) 下午5:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [haofeixu/aanet] ValueError: cannot reshape array of size 6139 into shape (540,960) (#65)





 
Hi @old-popsicle , could you please provide more info regarding the error, for example, the running script, thanks.

**Comment by haofeixu** [comment]
It seems that the error occurs when loading the ground truth disparity of Scene Flow dataset, maybe you can check whether your dataset is broken or the data is not loaded properly (e.g., the file path is not correct).

**Comment by old-popsicle** [comment]
My friend encountered this problem when running psmnet before, but when he put the batch_ size is set to 1, the problem is solved. However, the problem I encountered happened to be in batch_ Size is set to 1. Maybe, as you said, there's something wrong with my data set. I appreciate your willingness to solve my problem. Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haofei ***@***.***&gt;; 
发送时间: 2021年5月28日(星期五) 下午5:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [haofeixu/aanet] ValueError: cannot reshape array of size 6139 into shape (540,960) (#65)





 
It seems that the error occurs when loading the ground truth disparity of Scene Flow dataset, maybe you can check whether your dataset is broken or the data is not loaded properly (e.g., the file path is not correct).

**Comment by old-popsicle** [comment]
Hi，when I run predict.sh.the output image is a low density image.Could you help me solve it? I would appreciate it if you could help me solve it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "刘振国"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月28日(星期五) 晚上7:42
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [haofeixu/aanet] ValueError: cannot reshape array of size 6139 into shape (540,960) (#65)



 My friend encountered this problem when running psmnet before, but when he put the batch_ size is set to 1, the problem is solved. However, the problem I encountered happened to be in batch_ Size is set to 1. Maybe, as you said, there's something wrong with my data set. I appreciate your willingness to solve my problem. Thank you.




------------------ 原始邮件 ------------------
发件人: "Haofei ***@***.***&gt;; 
发送时间: 2021年5月28日(星期五) 下午5:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [haofeixu/aanet] ValueError: cannot reshape array of size 6139 into shape (540,960) (#65)





 
It seems that the error occurs when loading the ground truth disparity of Scene Flow dataset, maybe you can check whether your dataset is broken or the data is not loaded properly (e.g., the file path is not correct).
