### ISSUE TITLE
Train script for StereoNet feature extractor

### ISSUE THREAD

**Issue by a-akram-98** [haofeixu/aanet#66]
Can You please provide the script you used for training the StereoNet-based model and PSMNet model?
thank you, @haofeixu

**Comment by haofeixu** [comment]
Hi @a-akram-98 , I can't find the exact training scripts but you can refer to AANet's training script (https://github.com/haofeixu/aanet/blob/master/scripts/aanet_train.sh) and modify the model configs according to https://github.com/haofeixu/aanet/blob/master/scripts/stereonet-aa_inference.sh and https://github.com/haofeixu/aanet/blob/master/scripts/psmnet-aa_inference.sh
