### ISSUE TITLE
Results obtained using the pre-training model

### ISSUE THREAD

**Issue by old-popsicle** [haofeixu/aanet#68]
Hello, when I tested with the pre-training model provided by you, the output was not very good.
![image](https://user-images.githubusercontent.com/72902369/126585201-2763b011-b7e5-471b-8256-6dd0ca10d2f0.png)
Excuse me, what is the problem?
Or do you need to do some processing on this disparity map?
@haofeixu I would appreciate it if you could answer it.

**Comment by SLQ97** [comment]
I cannot download the pretrained,could you give me a solution?thank you!

**Comment by haofeixu** [comment]
This issue indicates that the model is not running properly, you might need to double check your environemnt is successfully installed, especially the CUDA op.
