### ISSUE TITLE
UserWarning: 000151_10_pred.png is a low contrast image warn

### ISSUE THREAD

**Issue by huangchengaihan** [haofeixu/aanet#69]
hello.
When I ran your pre-training model using the predict.sh file, I got a low concentration image warning.
You know what to do about it?

UserWarning: demo/pred/000151_10_pred.png is a low contrast image warn('%s is a low contrast image' % fname)

![1](https://user-images.githubusercontent.com/54969276/126636433-86fd0016-3030-4fcd-94bc-004fa4ca5a80.png)
@haofeixu

**Comment by haofeixu** [comment]
This issue indicates that the model is not running properly, you might need to double check your environemnt is successfully installed, especially the CUDA op.
