### ISSUE TITLE
performance without pseudo-labels

### ISSUE THREAD

**Issue by SamChuah** [haofeixu/aanet#7]
Hi, 

Great work and thanks for sharing the code. May I ask if you have the numbers for the performance of your model when trained with only the sparse KITTI ground truth or in other words without the pseudo-labels provided by other network?

**Comment by SamChuah** [comment]
Don't worry about it. I found it in the paper.

**Comment by SamChuah** [comment]
Hi,

May I know if the results of your work without pseudo ground truth you shared in your paper is evaluated by uploading the results to KITTI benchmark or by using the matlab script provided by KITTI? 

If you are evaluating using matlab, can you provide the list of testing images? 
Thank you

**Comment by haofeixu** [comment]
Hi @SamChuah ,

The results are evaluated by our python code https://github.com/haofeixu/aanet/blob/5e2359cfea9c38ebcddf5e750ec9ad1ac92725fc/model.py#L258-L262.
The validation split is available at https://github.com/haofeixu/aanet/blob/master/filenames/KITTI_2015_val.txt

**Comment by SamChuah** [comment]
Thanks for the swift reply. Do you know if there is any difference between your python code and the matlab script provided by KITTI?

**Comment by haofeixu** [comment]
The results should be very close if not exactly same, I cannot recall precisely. 
You can double check on your side by comparing the evaluation results.

**Comment by SamChuah** [comment]
Thank you very much :)
