### ISSUE TITLE
Dir not found.

### ISSUE THREAD

**Issue by Ashish-Github193** [haofeixu/aanet#71]
If you would like to use the pseudo ground truth supervision introduced in our paper, you can download the pre-computed disparity on KITTI 2012 and KITTI 2015 training set here: KITTI 2012, KITTI 2015.

For KITTI 2015, you should place disp_occ_0_pseudo_gt under kitti_2015/data_scene_flow/training.

Where would I paste "disp_occ_0_pseudo_gt"? and where is "kitti_2015/data_scene_flow/training"?

**Comment by haofeixu** [comment]
Hi @Ashish-Github193 , `kitti_2015/data_scene_flow/training` is from kitti 2015 stereo data. You can download from here: http://www.cvlibs.net/datasets/kitti/eval_scene_flow.php?benchmark=stereo and unzip it.
