### ISSUE TITLE
match_similarity参数

### ISSUE THREAD

**Issue by nicksunyang** [haofeixu/aanet#8]
# Matching similarity or matching cost
        cost_volume = cost_volume if self.match_similarity else -cost_volume
这个操作没有理解，可以解释一下吗？为什么要加负号？,PSMNet, GANet都不用加，Stereonet源代码也没有加负号

**Comment by haofeixu** [comment]
You can refer to the discussion here: https://github.com/JiaRenChang/PSMNet/issues/114
