### ISSUE TITLE
Undefined Symbol Error, most likely because i am using CUDA 11 instead of the intended CUDA 10

### ISSUE THREAD

**Issue by shamsulfakhar** [haofeixu/aanet#85]
I know I am supposed to use CUDA 10.0 for this, but my RTX 3060 requires me to use minimum CUDA 11, so here I am with a CUDA 11.8 and whenever I run `bash scripts/aanet_train.sh` I get this error:
>   File "train.py", line 8, in <module>
    import nets
  File "/home/sf/AANET/nets/__init__.py", line 1, in <module>
    from .aanet import AANet
  File "/home/sf/AANET/nets/aanet.py", line 4, in <module>
    from nets.feature import (StereoNetFeature, PSMNetFeature, GANetFeature, GCNetFeature,
  File "/home/sf/AANET/nets/feature.py", line 5, in <module>
    from nets.deform import DeformConv2d
  File "/home/sf/AANET/nets/deform.py", line 3, in <module>
    from nets.deform_conv import DeformConv, ModulatedDeformConv
  File "/home/sf/AANET/nets/deform_conv/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/sf/AANET/nets/deform_conv/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: /home/sf/AANET/nets/deform_conv/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

The error message suggests that there is an undefined symbol in the file `deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so`, which is being imported with the statement `from . import deform_conv_cuda`. The symbol `_ZNSt15__exception_ptr13exception_ptr10_M_releaseEv` is an exception handler likely a missing symbol in the library's dependencies. I assume this occur because that library was built with a different version of CUDA. Do you happen to have that library that is built using CUDA 11?

**Comment by haofeixu** [comment]
Unfortunately I didn't have the library with CUDA 11 since this project has finished for quite some time. 

Would you be interested in taking a look at our new stereo model: https://github.com/autonomousvision/unimatch, which has better performance and is implemented in pure pytorch.
