### ISSUE TITLE
how   to set input size

### ISSUE THREAD

**Issue by yyy809643573** [haofeixu/aanet#86]
how can  I set  the input size，when the new image size is not euqal with  training data size, using padding or crop ? it seems that crop or padding will  influence the stereo matching  result,is there any general ways ？

**Comment by haofeixu** [comment]
You can also try to resize to the training resolution for prediction and finally resize the output back to the original resolution (https://github.com/autonomousvision/unimatch/blob/master/evaluate_stereo.py#L782-L813).

**Comment by yyy809643573** [comment]
thank you!  I see that  in the  row  813 of evaluate_stereo.py  is  pred_disp = pred_disp * ori_size[-1] / float(inference_size[-1]),
when resizing back, predicted disp is only  considered in the width dimension， whether the height dimension  is needed to consider,thank you!

**Comment by haofeixu** [comment]
No since the displacement in the vertical direction is 0.
