### ISSUE TITLE
Number of outputs 

### ISSUE THREAD

**Issue by SamChuah** [haofeixu/aanet#9]
Hi, in your paper you mentioned three different scales are used (1/3, 1/6, 1/12). In term of loss function, you first bilinearly upsample your outputs and use the ground truth labels as well as the pseudo round truth labels together with the outputs to compute the loss of each resolution. Balancing term, lambda is also included. But at the end of section 4.2, you mentioned lambda1,2,3 = 1.0, lambda4 = 2/3, lambda5 = 1/3. 

I am wondering why are there 5 losses if you have only 3 outputs? Maybe I have misinterpreted something in your paper.

**Comment by haofeixu** [comment]
There are also two refinement modules to upsample the 1/3 resolution prediction to 1/2 and original resolutions. You can check the caption of Fig. 2 and Sec. 3.3 in our paper for more details.

**Comment by SamChuah** [comment]
Thank you!
