### ISSUE TITLE
why we get the wrong demo

### ISSUE THREAD

**Issue by wjmzbz** [haofeixu/aanet#90]
hi,feixu
nice job,
we want to use aanet as the real scene.But when we run the aanet_predict.sh,we didn't get the correct result as follows.Should I need to adjust some parameters?
![image](https://github.com/haofeixu/aanet/assets/94369850/aa0c70fb-7629-4d8a-b447-cb6636573a4d)

**Comment by wjmzbz** [comment]
Sorry, we have resolved this issue. It is an environment configuration error

**Comment by Yhhh77** [comment]
I'm also experiencing the same issue. Could you share how you resolved it?
